version: '3'
services:

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=group-finder-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017-27019:27017-27019
    volumes:
      - mongo_volume:/data/db
    command: mongod --quiet --logpath /dev/null   

  group-finder-api:
    build: ../group-finder-api
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - ../group-finder-api/src/:/app/src
      - ../group-finder-api/package.json:/app/package.json
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://root:root@mongodb:27017/group-finder-db?authSource=admin
    command: npm run dev         
            
volumes:
  mongo_volume: